### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by ghostilein** [haraldh/SunCalc#1]
Hello, I installed the Widget on Vivoactive HR and it's only Show "IQ!" Other widgets with GPS work like charm. Reinstallation does Not work.

**Comment by haraldh** [comment]
Can you see a "CIQ_LOG.txt" file on your watch? If yes, please paste the contents here.

**Comment by ghostilein** [comment]
Hello Harald,

I will look at home. I'm @ work. 


Mit freundlichen Grüßen 

Lars Horst

Mobil : +4915758305330
Privat:  +4945158697483
Fax:     +4945158697485

**Comment by haraldh** [comment]
and?

**Comment by ghostilein** [comment]
Difficult. sometimes it works sometimes it doesn´t.

I will post my log on github.

**Comment by haraldh** [comment]
Sieht eher nach Fehler von: "venu_master_clean" oder deinem Watchface aus.

**Comment by haraldh** [comment]
Allright, I'll review the code paths again.

**Comment by haraldh** [comment]
Please retry with version 7

**Comment by haraldh** [comment]
and?

**Comment by ghostilein** [comment]
All okay.... thanks ...

Mit freundlichen Grüßen 

Lars Horst

Mobil : +4915758305330
Privat:  +4945158697483
Fax:     +4945158697485
