### ISSUE TITLE
possible typo

### ISSUE THREAD

**Issue by jamorris** [haraldh/SunCalc#3]
In the Garmin Connect and Garmin IQ apps, the SunCalc settings for the last item is "Show astronomical Dawn" but I think that should be "Show astronomical Dusk". When it's the only time enabled I see "Astr. Dusk" on my watch so the widget displays correctly. The only issue seems to be with the text in Garmin Connect and Connect IQ. Thank you for this widget. It works well on my Forerunner 645M.

**Comment by haraldh** [comment]
You are right:

https://github.com/haraldh/SunCalc/blob/1c915efad5d38843b5b3214300f5880428ef362b/resources/settings.xml#L29

**Comment by haraldh** [comment]
Thanks!
